feat: /settings - 회원정보설정 1차 구현
EFUB-LakkuLakku/LakkuLakku-Back pull request #9
Opened 2022-07-15 15:57 UTC by SeojungH

resolves #8

2022-07-16 02:09 UTC, nitronium102 requested changes

2022-07-16 02:09 UTC, nitronium102 commented on src/main/java/com/efub/lakkulakku/domain/user/controller/SettingsController.java
> +    @PutMapping("/api/v1/settings")
controller 맨 위에 @RequestMapping("/api/v1/settings") 이런 식으로 적으면 root url을 설정할 수 있어요!
보통 위에 @RequestMapping으로 root url을 적고 밑에 하위 url을 적는 것 같습니다.

2022-07-16 02:09 UTC, nitronium102 commented on src/main/java/com/efub/lakkulakku/domain/user/controller/SettingsController.java
> +    }
여기에서 그냥 updatePasswordDto를 통째로 넘겨도 좋을 것 같아요

2022-07-22 04:56 UTC, SeojungH commented
- [ ] 리뷰 피드백 반영 후 수정

- [ ] 개인정보 변경에서 이메일 수정 삭제

- [ ] 비밀번호 변경 에러 핸들링 추가

2022-07-22 08:54 UTC, nitronium102 approved these changes

2022-07-23 14:25 UTC, merged